//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkSLAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTICIPER
    {
        public decimal NUMEMP { get; set; }
        public string CODESEMI { get; set; }
        public string CODEJOUR { get; set; }
    
        public virtual INSCRIT INSCRIT { get; set; }
    }
}
